export const TAGGR_TEST_ACTION = 'TAGGR_TEST_ACTION';
export const CREATE_NEW_PROJECT = 'CREATE_NEW_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DONE_CREATING = 'DONE_CREATING';
