export const TAGGR_TEST_ACTION = 'TAGGR_TEST_ACTION';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const CREATE_PROJECT_START = 'CREATE_PROJECT_START';
export const CREATE_PROJECT_FINISH = 'CREATE_PROJECT_FINISH';
